version: '3.1'

services:
  mongo:
    build:
        context: ./db
        dockerfile: Dockerfile
    #image: yooml/mongo-hudex-dev:v3
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    networks:
      - mynetwork

  nestjs:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
    - 3000:3000
    networks:
      - mynetwork

volumes:
  mongodata:

networks:
  mynetwork:
